[platformio]
default_envs = esp32c3

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
  adafruit/Adafruit GFX Library @ ^1.12.1
  adafruit/Adafruit SSD1306 @ ^2.5.13
  knolleary/PubSubClient @ ^2.8
  bblanchon/ArduinoJson @ ^7.3.0
  https://github.com/FluxGarage/RoboEyes.git
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
